### PR TITLE
Change new Buffer() to Buffer.from()

### PR DESCRIPTION
**Pull request by styfle**
This fixes node.js v6.x.x and newer but will only work on node.js v5.10.0 and newer.

### CODE REVIEW

**Comment by mafintosh** [comment]
:+1: I saw you pinged me on Twitter about another issue you had opened? Interested in helping maintain this module? (perfectly fine to say no)

**Comment by mafintosh** [comment]
6.0.0

**Comment by styfle** [comment]
@mafintosh Thanks!

I would be willing to help however my experience with Buffers and Streams is limited to [one side project](https://github.com/styfle/magnemite) so I might not be most qualified. But I know my way around node and npm.

**Comment by mafintosh** [comment]
Added you as collab in any case :) Let me know if you wanna be added to npm

**Comment by styfle** [comment]
@mafintosh Yes please add me to npm

**Pull request merged**
