### PR TITLE
Include SSL option in README

### PR DESCRIPTION
**Pull request by gilesvangruisen**

### CODE REVIEW

**Comment by styfle** [comment]
@gilesvangruisen This changes more than just the README. Maybe you should separate into two PRs.

**Comment by gilesvangruisen** [comment]
@styfle Oh hm, thanks for the heads up. I only intended to change the readme, so I'm not quite sure what happened there!

**Comment by styfle** [comment]
It looks like you added `standard` which reformatted everything.

I'm going to go ahead and close this PR and you can open a new one with just the change to the README.md.

Thanks! 😄

**Comment by gilesvangruisen** [comment]
@styfle ha, weird. I don't remember doing that but it's been long enough I could have forgotten! Or maybe I branched off a fork 🤷‍♂️ 

PR incoming, thanks for the bump!

**Pull request closed without merging**
